routes:
  _default: mock
  ACT_APPROACH_SLOWLY_SIDEWAYS: agv
  ACT_ASK_CUDDLE: agv
  ACT_BARK_AND_LIE_DOWN_IF_NO_CHARGER: agv
  ACT_BARK_AT_OBJECT: agv
  ACT_BARK_OR_WHINE_BRIEFLY: agv
  ACT_BARK_TENSE: agv
  ACT_BASIC_LIE_DOWN: agv
  ACT_BASIC_SIT: agv
  ACT_BASIC_STAND: agv
  ACT_BASIC_WAIT: agv
  ACT_BAT_TOY: agv
  ACT_BITE_AND_SHAKE_SLIPPERS_SOCKS_OR_TOY: agv
  ACT_BITE_DELIVERY_BOX: agv
  ACT_BONE_DANCE: agv
  ACT_BUMP_OTHER_GENTLY_WITH_RELAXED_BODY: agv
  ACT_BURP: agv
  ACT_CARRY_AND_DROP_OBJECT_AGAIN: agv
  ACT_CARRY_AND_HIDE_OBJECT: agv
  ACT_CARRY_BOWL_AND_FOLLOW_OWNER: agv
  ACT_CARRY_DELIVERY_BOX_TO_PERSON: agv
  ACT_CARRY_LEASH_TO_OWNER: agv
  ACT_CARRY_SLIPPERS_SOCKS_OR_TOY_TO_OWNER: agv
  ACT_CARRY_TISSUE_TO_PERSON: agv
  ACT_CARRY_TOY_AND_WAG_TAIL_IN_FRONT_OF_OWNER: agv
  ACT_CHANGE_POSTURE: agv
  ACT_CHASE_TAIL: agv
  ACT_CHECK_OWNER: agv
  ACT_CHEW_OR_CARRY_FOOD: agv
  ACT_CIRCLE_AROUND: agv
  ACT_CIRCLE_AROUND_OWNER: agv
  ACT_CIRCLE_EMPTY_BOWL_OR_WATER_DISH: agv
  ACT_CLING_LEG: agv
  ACT_COMFY_STRETCH: agv
  ACT_COVER_EYES: agv
  ACT_CRAWL_THROUGH_LOW_GAP: agv
  ACT_FETCH_LEASH: agv
  ACT_FETCH_TOY: agv
  ACT_FIND_PLACE_TO_LIE_DOWN: agv
  ACT_FLIP_BODY: agv
  ACT_FOLLOW_AND_STAY_CLOSE_TO_OWNER: agv
  ACT_FREEZE_SHAKE: agv
  ACT_GENTLY_MOUTH_PANTS_OR_HAND: agv
  ACT_GETUP_BOUNCE: agv
  ACT_GETUP_CRAWL: agv
  ACT_GETUP_ROLL: agv
  ACT_GETUP_SIT: agv
  ACT_GETUP_STRETCH: agv
  ACT_GUARD_DOOR: agv
  ACT_HIDE_BEHIND: agv
  ACT_HIDE_SHRINK: agv
  ACT_IGNORE_DELIVERY_BOX: agv
  ACT_IGNORE_DOOR: agv
  ACT_IGNORE_SLIPPERS_SOCKS_OR_TOY: agv
  ACT_IGNORE_TISSUE: agv
  ACT_IGNORE_TRASH_CAN: agv
  ACT_INTERACT_APPROACH_OWNER: agv
  ACT_INTERACT_EXPLORE: agv
  ACT_INTERACT_FOLLOW_OWNER: agv
  ACT_INTERACT_GIVE_PAW: agv
  ACT_INTERACT_HIGH_FIVE: agv
  ACT_INTERACT_RETURN_OWNER: agv
  ACT_JUMP_PAW: agv
  ACT_KNOCK_OVER_OBJECT: agv
  ACT_LEAN_AGAINST_DOOR: agv
  ACT_LICK: agv
  ACT_LICK_AND_SWALLOW: agv
  ACT_LICK_FACE: agv
  ACT_LICK_FOOD: agv
  ACT_LICK_FUR_OR_PAWS: agv
  ACT_LICK_LIPS_OR_NOSE: agv
  ACT_LICK_LIPS_OR_NOSE_AND_LEAVE: agv
  ACT_LICK_PAWS_OR_FUR: agv
  ACT_LICK_SELF: agv
  ACT_LIE_BESIDE_OTHER_ANIMAL: agv
  ACT_LIE_BY_DOOR: agv
  ACT_LOWER_HEAD_AND_APPROACH_BOWL: agv
  ACT_LOWER_HEAD_FLOP_EARS_WAG_TAIL: agv
  ACT_NIBBLE_OBJECT: agv
  ACT_NIP_PLAYFUL: agv
  ACT_NON_INTERACT_EXPLORE: agv
  ACT_NUDGE_OR_RUB_AGAINST_OWNER_HAND: agv
  ACT_NUDGE_OWNER_AND_LOOK_AT_FOOD_OR_DOOR: agv
  ACT_NUZZLE_BODY: agv
  ACT_NUZZLE_HEAD: agv
  ACT_PACE: agv
  ACT_PATROL: agv
  ACT_PATROL_ALONG_WALL: agv
  ACT_PAUSE_AND_LOOK_AT_OWNER: agv
  ACT_PAW_AT_BOWL_AND_WAIT_FOR_FOOD: agv
  ACT_PAW_AT_BOWL_FOR_FOOD: agv
  ACT_PAW_AT_BOWL_OR_TREAT_CABINET: agv
  ACT_PAW_AT_MUZZLE: agv
  ACT_PAW_AT_OWNER: agv
  ACT_PAW_AT_SLIPPERS_SOCKS_OR_TOY: agv
  ACT_PAW_GENTLY_AT_OTHER: agv
  ACT_PAW_LEG: agv
  ACT_PLACE_FRONT_PAWS_ON_OWNER_FOR_ATTENTION: agv
  ACT_PLAY_BOW: agv
  ACT_POUNCE_ON_SLIPPERS_SOCKS_OR_TOY: agv
  ACT_POUNCE_OR_SIDE_HOP_GENTLY: agv
  ACT_PURR: agv
  ACT_PUSH_OBJECT_WITH_PAW: agv
  ACT_RETURN_TO_CHARGER: agv
  ACT_RETURN_TO_DOG_BED_FOR_CHARGING: agv
  ACT_ROLL_OVER_FOR_BELLY_RUB: agv
  ACT_RUB_AGAINST_LEG_OR_LEAN_ON_OWNER: agv
  ACT_RUB_BODY_AGAINST_OBJECT: agv
  ACT_RUMMAGE_THROUGH_TRASH_CAN: agv
  ACT_RUN_AWAY_AND_LOOK_BACK: agv
  ACT_RUN_IN_CIRCLES_OR_CHASE: agv
  ACT_RUN_IN_CIRCLES_OR_ZOOMIES: agv
  ACT_SCRATCH_BED_OR_GROUND: agv
  ACT_SCRATCH_DELIVERY_BOX_WITH_PAW: agv
  ACT_SCRATCH_DOOR: agv
  ACT_SCRATCH_EAR_WITH_HIND_LEG: agv
  ACT_SCRATCH_FOOD: agv
  ACT_SCRATCH_OBJECT_GENTLY: agv
  ACT_SCRATCH_SOIL_OR_GROUND: agv
  ACT_SCRATCH_TISSUE_WITH_PAW: agv
  ACT_SEEK_PETS: agv
  ACT_SHAKE_HEAD: agv
  ACT_SHAKE_OFF_WATER: agv
  ACT_SHAKE_TOY: agv
  ACT_SHOW_BELLY: agv
  ACT_SIDE_HOP_WITH_PLAY_POSTURE: agv
  ACT_SIT_BY_DOOR_AND_LOOK_BACK_AT_OWNER: agv
  ACT_SIT_IN_FRONT_OF_OWNER_AND_LOOK_UP: agv
  ACT_SLEEP_BY_FEET: agv
  ACT_SLEEP_CURLED_UP: agv
  ACT_SLEEP_ON_BACK: agv
  ACT_SLEEP_ON_SIDE: agv
  ACT_SLEEP_ON_SIDE_CURLED_UP: agv
  ACT_SLEEP_ON_STOMACH: agv
  ACT_SLOW_DOWN_IN_RESPONSE_TO_OWNER: agv
  ACT_SNIFF_AND_CIRCLE_AT_TOILET_SPOT: agv
  ACT_SNIFF_AROUND_DOOR: agv
  ACT_SNIFF_BOWL_AND_WAIT_FOR_FOOD: agv
  ACT_SNIFF_BOWL_RIM_AND_WAIT_FOR_FOOD: agv
  ACT_SNIFF_BUTT_OR_TAIL: agv
  ACT_SNIFF_DELIVERY_BOX: agv
  ACT_SNIFF_EXCREMENT: agv
  ACT_SNIFF_FACE_OR_EARS: agv
  ACT_SNIFF_GROUND_FOR_CRUMBS: agv
  ACT_SNIFF_GROUND_FOR_CRUMBS_AND_LEAVE: agv
  ACT_SNIFF_OBJECT: agv
  ACT_SNIFF_SLIPPERS_SOCKS_OR_TOY: agv
  ACT_SNIFF_TISSUE: agv
  ACT_SNIFF_TOWARD_OTHER_ANIMAL: agv
  ACT_SNIFF_TRASH_CAN: agv
  ACT_SPIN_FRONT: agv
  ACT_SPIN_IN_PLACE: agv
  ACT_SPLOOT: agv
  ACT_SPLoot_LIE_DOWN: agv
  ACT_SQUAT_AND_ELIMINATE: agv
  ACT_STAND_AND_SCRATCH_HIGH: agv
  ACT_STAND_UP_AND_PAW_AT_OWNER_LEG: agv
  ACT_STOP_OBSERVE_AND_TILT_HEAD: agv
  ACT_STRETCH: agv
  ACT_STRETCH_BODY: agv
  ACT_SYSTEM_EMERGENCY_STOP: agv
  ACT_TOUCH_NOSE_OR_HEAD_GENTLY: agv
  ACT_TOUCH_OR_CARRY_OBJECT_WITH_MOUTH: agv
  ACT_TRICK_PLAY_DEAD: agv
  ACT_TRICK_ROLL_OVER: agv
  ACT_TRICK_SPIN: agv
  ACT_TROT_BOUNCE: agv
  ACT_TROT_STOP_AND_SNIFF: agv
  ACT_TUCK_TAIL: agv
  ACT_TWITCH_OR_KICK_LEGS: agv
  ACT_VISUALLY_TRACK_FOOD_IN_HAND: agv
  ACT_WAG_TAIL: agv
  ACT_WAIT_BY_BOWL_OR_TREAT_CABINET: agv
  ACT_WALK_AWAY_OR_LIE_DOWN: agv
  ACT_WALK_AWAY_OR_SHAKE_HEAD: agv
  ACT_WALK_SLOWLY_AND_SNIFF_GROUND: agv
  ACT_WHIMPER: agv
  ACT_WHINE: agv
  ACT_WHINE_AND_WAIT_FOR_FOOD: agv
  ACT_WHINE_OR_VOCALIZE_SOFTLY: agv
  ACT_WHINE_SOFTLY: agv
  ACT_WINK: agv
  ACT_YAWN: agv
  ACT_ZOOMIES: agv
  ACT_ZOOMIE_CIRCLE: agv
  ACT_INTERACT_RESPOND_CALL: wake_orientation
  ACT_OBJECT_BRING: perception_navigation_manipulation
  ACT_OBJECT_FETCH: perception_navigation_manipulation
